### ISSUE TITLE
Import is "unused", althow it's used in @var annotation 

### ISSUE THREAD

**Issue by EdaCZ** [Haehnchen/idea-php-annotation-plugin#136]
PhpStorm 2018.3 EAP
Build #PS-183.4139.15, built on October 31, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-38-generic

Plugin version: 5.3.3

See screenshots please:

![screenshot from 2018-11-04 18-33-54](https://user-images.githubusercontent.com/1671637/47967763-640fb280-e061-11e8-89e2-b9a8dc246c55.png)
![screenshot from 2018-11-04 18-34-06](https://user-images.githubusercontent.com/1671637/47967764-640fb280-e061-11e8-9956-3d26c993643e.png)

Interesting is that whether I remove `namespace` statement, error disappears.
![screenshot from 2018-11-04 18-43-22](https://user-images.githubusercontent.com/1671637/47967784-915c6080-e061-11e8-89f5-3f3f74540e80.png)

I am not sure, whether this is bug in plugin, PhpStorm or I am missing something.

**Comment by cedricziel** [comment]
It's not about the plugin, the message states an import is not necessary, since both classes reside in the same package. An import is superfluous in this case.

BTW, regarding semantics and the fact that the import is unused - thats true since package local classes need no import. Maybe not an optimal inspection, but still true semantically. This would vanish if you'd alias the class.

**Comment by Haehnchen** [comment]
we are hard in touch with the PhpStorm functionality here `https://github.com/Haehnchen/idea-php-annotation-plugin/blob/master/src/main/java/de/espend/idea/php/annotation/reference/DocTagNameAnnotationReferenceContributor.java#L92`.
As reported release is EAP and this inspection is more fancy in this version maybe there is a change by PhpStorm in this pre-release
