### ISSUE TITLE
Import is "unused" if Annotations are not separated by newline

### ISSUE THREAD

**Issue by jhard** [Haehnchen/idea-php-annotation-plugin#166]
PhpStorm 2019.3
Build #PS-193.5233.101, built on November 27, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-72-generic
Plugin version 6.2.2

On a Doctrine Entity with 
```
use \Doctrine\ORM\Mapping\Entity as Entity;
use \Doctrine\ORM\Mapping\Table as Table;

/**
 * @Entity @Table(name="test")
 */
class Test
{
}
```
Table is marked as unused.
Changing the docblock to include
```
 * @Entity
 * @Table(name="test")
```
Works fine.

Changing it to 
```
* @Entity(@Table(name="test"))
```
will make the plugin realize Table was used, but has a different meaning and Doctrine will complain because Table cannot be used on Entity, but only on the class itself.

I'm not sure whether Doctrine's AnnotationReader is too generous when accepting space-separated annotations or this plugin should accept it as well. Feel free to close this issue if the unexpected behavior is on Doctrine's side.

It's not a huge deal, you can just use a line break, or import Mapping as ORM and use `@ORM\Entity` and `@ORM\Table`. However, having `@ORM\Entity @ORM\Table(name="test")` won't find the declaration of Table.

**Comment by Haehnchen** [comment]
I have never seen this usage, but good to know that its working. The problem here is that PhpStorm is not parsing this correctly. Its simply only object. :)

Feel free to report this issue on PhpStorm issues tracker and link it here.
From this plugin point of no fix is possible here.

![image](https://user-images.githubusercontent.com/1011712/83290180-8a1e1a00-a1e6-11ea-87ce-4555f8a1cd7e.png)
