### ISSUE TITLE
Invalid PhpDoc name completion since PhpStorm 2020.2

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-annotation-plugin#209]
Check where PhpDoc name completion completion is coming from, happening since PhpStorm 2020.2.

https://twitter.com/januszmk6/status/1291577027602964480

![image](https://user-images.githubusercontent.com/1011712/89813972-c48b2800-db42-11ea-96cd-054848df623c.png)

**Comment by khkramer** [comment]
![image](https://user-images.githubusercontent.com/7979637/97975681-c7a45600-1dc9-11eb-87f2-f76a7614e099.png)

Same problem here, really annoying..
However I wish PHPStorm just offered the option to disable their built-in autocomplete for annotations since that's where the upper suggestions come from and they are utterly useless compared to the ones this plugin provides

**Comment by Haehnchen** [comment]
maybe i can upvote the plugin ones ;)

**Comment by AlexeyKosov** [comment]
really pisses me off :( anybody found a workaround?

**Comment by AlexeyKosov** [comment]
> 
> maybe i can upvote the plugin ones ;)

Could you please just let us know on which end the issue is? Is it something that can be fixed in the plugin or we rather should create a ticket for PhpStorm itself?

**Comment by Haehnchen** [comment]
so done ;)
