### ISSUE TITLE
Fails to recognize import useful for PHPDoc Annotation(s), PHPStorm 2016.2

### ISSUE THREAD

**Issue by skvskv** [Haehnchen/idea-php-annotation-plugin#59]
The plugin falsely considers an import of a class unused provided the class is mentioned in PHPDoc Annotations and never addressed in code in any way.

It has never been this way in PHPStorm 2016.1 and appeared after update to 2016.2
![screenshot](https://cloud.githubusercontent.com/assets/7080404/16840926/44335d02-4a01-11e6-89a3-803a457314a7.png)

**Comment by King2500** [comment]
Maybe this has to do with the recently added "alias" feature.

What happens if you use:

```php
use Zend\Form\Annotation as Annotation;
```

**Comment by upyx** [comment]
I have the same problem. "Alias" feature not resolve it. Also I cannot check and replace all imports in project. However PHPStorm don't check a import with alias but only if alias differs from the import.

**Comment by PeekAndPoke** [comment]
I have the same issue with IntelliJ IDEA 2016.2. This used to work fine in previous versions. I fix is highly appreciated !

**Comment by skvskv** [comment]
Everyone is also welcome to pick on JetBrains on their youtrack:
Vote for https://youtrack.jetbrains.com/issue/WI-32557

**Comment by Haehnchen** [comment]
note for me:
 - there is a blacklist for classes named: "Annotation"; conflicts?
 - `Zend\Form\Annotation` is just a folder

**Comment by nsknewbie** [comment]
Same for me!

Noticed some things:

1. `use Zend\Form\Annotation;` marked as unused
2. `use Zend\Form\Annotation as Annotation;` still marked as unused
3. `use Zend\Form\Annotation as Test;` is NOT marked as unused even if there are no uses in annotations

Seems giving an alias with different name is the only working workaround for now

**Comment by skvskv** [comment]
@Haehnchen, may it be fixed at all?

**Comment by Haehnchen** [comment]
so indeed as testing says PhpStorm 2016.2 issue

**Comment by skvskv** [comment]
@Haehnchen , thank you for making the matter clear.
Would you be so kind and support reopening [the issue on youtrack](https://youtrack.jetbrains.com/issue/WI-32557)?

**Comment by Haehnchen** [comment]
... will validate issue tomorrow

**Comment by Haehnchen** [comment]
fixed by  #59

**Comment by artspb** [comment]
1. Since 2016.2 PhpStorm partially [supports](https://youtrack.jetbrains.com/issue/WI-15377) namespace imports. `Zend\Form\Annotation` is a namespace thus its import can be removed if unused. Let's take a look on the cases by @nsknewbie:

    1.1. `use Zend\Form\Annotation;` marked as unused because the plugin doesn't provide with the references to this element.
    1.2. `use Zend\Form\Annotation as Annotation;` is technically the same import as the previous one.
    1.3. `use Zend\Form\Annotation as Test;` is not removed because PS [doesn't support](https://youtrack.jetbrains.com/issue/WI-32140) namespace aliases ATM.

2. My sentence "the plugin doesn't provide with the references to this element" is not fully correct. Actually the plugin [does provide](https://github.com/Haehnchen/idea-php-annotation-plugin/blob/master/src/de/espend/idea/php/annotation/reference/DocTagNameAnnotationReferenceContributor.java) with the references. But it's not enough because the reference must also properly implement `#isReferenceTo()` method. It can be done in many ways, here's the one of them #63.

**Comment by skvskv** [comment]
@artspb, many thanks! Accomplishment much appreciated!
